# Generated by Django 5.2.5 on 2025-11-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_community_challenge_userchallenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
